name:                bear-to-org
version:             0.1.0.0
github:              "deff7/bear-to-org"
license:             BSD3
author:              "Sergey Malenkov"
maintainer:          "def.sergey@gmail.com"
copyright:           "2020 Sergey Malenkov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deff7/bear-to-org#readme>

dependencies:
- base >= 4.7 && < 5
- text
- pandoc
- pandoc-types
- uuid
- directory
- filepath
- random
- containers
- uri-encode
- optparse-applicative

library:
  source-dirs: src

executables:
  bear-to-org-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bear-to-org

tests:
  bear-to-org-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bear-to-org
