name:                zettel-migrator
version:             0.1.0.0
github:              "githubuser/zettel-migrator"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/zettel-migrator#readme>

dependencies:
- base >= 4.7 && < 5
- text
- pandoc
- pandoc-types
- uuid
- directory
- filepath
- random
- containers
- uri-encode
- optparse-applicative

library:
  source-dirs: src

executables:
  zettel-migrator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zettel-migrator

tests:
  zettel-migrator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zettel-migrator
